[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "@netlify/plugin-lighthouse"

    # to audit a path other than /
    # route1 audit will use the top level thresholds
    [[plugins.inputs.audits]]
    paths =  [
      "/",
      "liquidity/all-pools",
    "wallet/assets",
    ] 


 