[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "@netlify/plugin-lighthouse"

    [[plugins.inputs.audits]]
        path = "/"
        
    [[plugins.inputs.audits]]
       path = "liquidity/all-pools"



 