[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "@netlify/plugin-lighthouse"

    # to audit a path other than /
    # route1 audit will use the top level thresholds
    [[plugins.inputs.audits]]
    path = "liquidity/all-pools"


    output_path = "reports/liquidity/all-pools.html"

 